name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build Openify
        run: >
          xcodebuild
          -project Openify.xcodeproj
          -scheme Openify
          -destination 'platform=macOS'
          -configuration Debug
          -derivedDataPath build/DerivedData
          CODE_SIGNING_ALLOWED=NO
          CODE_SIGNING_REQUIRED=NO
          CODE_SIGN_IDENTITY=""
          build

      - name: Package Openify.app
        run: |
          mkdir -p build/artifacts
          cp -R "build/DerivedData/Build/Products/Debug/Openify.app" "build/artifacts/Openify.app"
          hdiutil create -volname "Openify" -srcfolder "build/artifacts/Openify.app" -ov -format UDZO "build/artifacts/Openify.dmg"

      - name: Upload Openify DMG
        uses: actions/upload-artifact@v4
        with:
          name: Openify-dmg
          path: build/artifacts/Openify.dmg
